theme: jekyll-theme-minimal
title: CodeJourneyer homepage
description: I'm not an expert; I'm just learning.

[andrii.romanenko.js@gmail.com](mailto:andrii.romanenko.js@gmail.com)
[@Andrii_Romanenko](https://t.me/Andrii_Romanenko)
[My Linkedin](https://www.linkedin.com/in/romanenko--andrii/)
[My instagram](https://www.instagram.com/romanenko_ipo/)
